stages:
  # initialize_environment:
  #   cmd: make init
  #   deps:
  #     - setup.sh
  #     - requirements-app.txt
  #     - environment.yml
  #     - .envrc
  #     - xbert/
  # convert_longformer:
  #   cmd: $PY_CONDA custom_models/roberta_to_longformer.py
  filter_text_notes:
    cmd: $PY_CONDA pipeline/filter_notes.py
    deps:
      - pipeline/filter_notes.py
      - data/mimiciii-14/NOTEEVENTS.csv.gz
    outs:
      - data/intermediary-data/filtered_notes/NOTEEVENTS.FILTERED.csv.gz
  prepare_for_xbert:
    cmd: $PY_CONDA pipeline/xbert_preprocessing.py
    deps:
      - pipeline/xbert_preprocessing.py
      - pipeline/format_data_for_training.py
      - data/ICD_general_equivalence_mapping.csv
      - data/mimiciii-14/DIAGNOSES_ICD.csv.gz
      - data/mimiciii-14/PROCEDURES_ICD.csv
      - data/mimiciii-14/D_ICD_DIAGNOSES.csv.gz
      - data/mimiciii-14/D_ICD_PROCEDURES.csv
      - data/intermediary-data/filtered_notes/NOTEEVENTS.FILTERED.csv.gz
    params:
      - prepare_for_xbert.subsampling
      - prepare_for_xbert.icd_version
      - prepare_for_xbert.diag_or_proc
    outs:
      - data/intermediary-data/df_train.pkl
      - data/intermediary-data/df_test.pkl
      - data/intermediary-data/xbert_inputs/label_map.txt
      - data/intermediary-data/xbert_inputs/train_raw_texts.txt
      - data/intermediary-data/xbert_inputs/test_raw_texts.txt
      # - data/intermediary-data/xbert_inputs/X.trn.npz
      # - data/intermediary-data/xbert_inputs/X.tst.npz
      - data/intermediary-data/xbert_inputs/Y.trn.npz
      - data/intermediary-data/xbert_inputs/Y.tst.npz
  xbert_label_embedding:
    cmd: ./run_preprocess_label.sh
    deps:
      - run_preprocess_label.sh
      - xbert/preprocess.py
      - data/intermediary-data/xbert_inputs/label_map.txt
      - data/intermediary-data/xbert_inputs/train_raw_texts.txt
      - data/intermediary-data/xbert_inputs/test_raw_texts.txt
      # - data/intermediary-data/xbert_inputs/X.trn.npz
      # - data/intermediary-data/xbert_inputs/X.tst.npz
      - data/intermediary-data/xbert_inputs/Y.trn.npz
      - data/intermediary-data/xbert_inputs/Y.tst.npz
    outs:
      - data/intermediary-data/xbert_outputs/proc_data/L.pifa-tfidf.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.trn.pifa-tfidf-s0.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.tst.pifa-tfidf-s0.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/indexer/code.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/indexer/config.json
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s1/indexer/code.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s1/indexer/config.json
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s2/indexer/code.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s2/indexer/config.json
  xbert_feat_embedding:
    cmd: ./run_preprocess_feat.sh
    deps:
      - run_preprocess_feat.sh
      - xbert/preprocess.py
      - data/intermediary-data/xbert_inputs/train_raw_texts.txt
      - data/intermediary-data/xbert_inputs/test_raw_texts.txt
      # - data/intermediary-data/xbert_inputs/X.trn.npz
      # - data/intermediary-data/xbert_inputs/X.tst.npz
      - data/intermediary-data/xbert_inputs/Y.trn.npz
      - data/intermediary-data/xbert_inputs/Y.tst.npz
    params:
      - max_seq_len
    outs:
      - data/intermediary-data/xbert_outputs/proc_data/X.trn.tomodel.pkl
      - data/intermediary-data/xbert_outputs/proc_data/X.tst.tomodel.pkl
  xbert_model_training:
    cmd: ./run_transformer_train.sh
    deps:
      - xbert/transformer.py
      - run_transformer_train.sh
      - data/intermediary-data/xbert_outputs/proc_data/X.trn.tomodel.pkl
      - data/intermediary-data/xbert_outputs/proc_data/X.tst.tomodel.pkl
      - data/intermediary-data/xbert_outputs/proc_data/L.pifa-tfidf.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.trn.pifa-tfidf-s0.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.tst.pifa-tfidf-s0.npz
    params:
      - max_seq_len
    outs:
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/training_args.bin
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/pytorch_model.bin
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/config.json
  xbert_trained_model_prediction:
    cmd: ./run_transformer_training_prediction.sh
    deps:
      - run_transformer_training_prediction.sh
      - data/intermediary-data/xbert_outputs/proc_data/X.trn.tomodel.pkl
      - data/intermediary-data/xbert_outputs/proc_data/X.tst.tomodel.pkl
      - data/intermediary-data/xbert_outputs/proc_data/L.pifa-tfidf.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.trn.pifa-tfidf-s0.npz
      - data/intermediary-data/xbert_outputs/proc_data/C.tst.pifa-tfidf-s0.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/training_args.bin
    params:
      - max_seq_len
    outs:
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/C_trn_pred.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/C_tst_pred.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/trn_embeddings.npy
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/tst_embeddings.npy      
  xbert_ranker_and_eval:
    cmd: ./run_transformer_predict.sh
    deps:
      - xbert/ranker.py
      - xbert/evaluator.py
      - run_transformer_predict.sh
      # - data/intermediary-data/xbert_inputs/X.trn.npz
      # - data/intermediary-data/xbert_inputs/X.tst.npz
      - data/intermediary-data/xbert_inputs/Y.trn.npz
      - data/intermediary-data/xbert_inputs/Y.tst.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/C_trn_pred.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/C_tst_pred.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/trn_embeddings.npy
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/matcher/tst_embeddings.npy
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/indexer/code.npz
    outs:
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/ranker/tst.pred.npz
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/ranker/param.json
      - data/intermediary-data/xbert_outputs/pifa-tfidf-s0/ranker/0.model
    metrics:
      - eval.json
