stages:
  prepare_for_xbert:
    cmd: python pipeline/xbert_preprocessing.py
    deps:
    - ../data/ICD_general_equivalence_mapping.csv
    - ../data/mimiciii-14/DIAGNOSES_ICD.csv.gz
    - ../data/mimiciii-14/D_ICD_DIAGNOSES.csv.gz
    - pipeline/xbert_preprocessing.py
    outs:
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/label_map.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/train_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/test_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.tst.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.tst.npz
