stages:
  prepare_for_xbert:
    cmd: python pipeline/xbert_preprocessing.py
    deps:
    - ../data/ICD_general_equivalence_mapping.csv
    - ../data/mimiciii-14/DIAGNOSES_ICD.csv.gz
    - ../data/mimiciii-14/D_ICD_DIAGNOSES.csv.gz
    - pipeline/xbert_preprocessing.py
    outs:
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/label_map.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/train_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/test_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.tst.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.tst.npz
  xbert_label_embedding:
    cmd: cd ./auto-icd-transformers && ./run_preprocess_label.sh
    deps:
    - auto-icd-transformers/run_preprocess_label.sh
    - auto-icd-transformers/environment.yml
    # from prepare_for_xbert... TODO: Use an anchor/alias, if thats supported...
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/label_map.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/train_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/test_raw_labels.txt
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/X.tst.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.trn.npz
    - ../data/intermediary-data/xbert_inputs/mimiciii-14/Y.tst.npz
    outs:
    - ../data/intermediary-data/xbert_outputs/proc_data/L.pifa-tfidf.npz
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s0/indexer/code.npz
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s0/indexer/config.json
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s1/indexer/code.npz
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s1/indexer/config.json
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s2/indexer/code.npz
    - ../data/intermediary-data/xbert_outputs/pifa-tfidf-s2/indexer/config.json
    - ../data/intermediary-data/xbert_outputs/proc_data/C.trn.pifa-tfidf-s0.npz
    - ../data/intermediary-data/xbert_outputs/proc_data/C.tst.pifa-tfidf-s0.npz