prepare_for_xbert:
  subsampling: false
xbert_feat_embedding:
  max_seq_len: 512
xbert_model_training:
  max_steps: 1000
  warmup_steps: 100
  logging_steps: 50
  learning_rate: 0.00005
  max_seq_len: 512
xbert_trained_model_prediction:
  max_seq_len: 512
